export const mockBanco = [
    { nome: 'Arroz', codigo: 1, preco: 20.0, quantidade: 10 },
    { nome: 'Feijão', codigo: 2, preco: 8.5, quantidade: 20 },
    { nome: 'Macarrão', codigo: 3, preco: 5.0, quantidade: 15 },
    { nome: 'Óleo', codigo: 4, preco: 6.0, quantidade: 25 },
    { nome: 'Açúcar', codigo: 5, preco: 4.5, quantidade: 30 },
    { nome: 'Café', codigo: 6, preco: 10.0, quantidade: 12 },
    { nome: 'Leite', codigo: 7, preco: 3.5, quantidade: 18 },
    { nome: 'Manteiga', codigo: 8, preco: 8.0, quantidade: 9 },
    { nome: 'Farinha', codigo: 9, preco: 4.0, quantidade: 22 },
    { nome: 'Molho de Tomate', codigo: 10, preco: 3.75, quantidade: 28 },
    { nome: 'Sal', codigo: 11, preco: 1.5, quantidade: 40 },
    { nome: 'Biscoito', codigo: 12, preco: 2.0, quantidade: 35 },
    { nome: 'Refrigerante', codigo: 13, preco: 6.5, quantidade: 16 },
    { nome: 'Suco', codigo: 14, preco: 5.5, quantidade: 14 },
    { nome: 'Carne', codigo: 15, preco: 25.0, quantidade: 8 },
    { nome: 'Frango', codigo: 16, preco: 12.5, quantidade: 10 },
    { nome: 'Peixe', codigo: 17, preco: 15.0, quantidade: 7 },
    { nome: 'Salsicha', codigo: 18, preco: 6.0, quantidade: 20 },
    { nome: 'Presunto', codigo: 19, preco: 7.5, quantidade: 10 },
    { nome: 'Queijo', codigo: 20, preco: 12.0, quantidade: 15 },
    { nome: 'Pão', codigo: 21, preco: 4.0, quantidade: 25 },
    { nome: 'Batata', codigo: 22, preco: 3.0, quantidade: 30 },
    { nome: 'Tomate', codigo: 23, preco: 2.5, quantidade: 40 },
    { nome: 'Cebola', codigo: 24, preco: 1.75, quantidade: 50 },
    { nome: 'Alho', codigo: 25, preco: 4.0, quantidade: 18 },
    { nome: 'Cenoura', codigo: 26, preco: 2.8, quantidade: 35 },
    { nome: 'Maçã', codigo: 27, preco: 3.5, quantidade: 25 },
    { nome: 'Banana', codigo: 28, preco: 2.0, quantidade: 40 },
    { nome: 'Laranja', codigo: 29, preco: 3.0, quantidade: 30 },
    { nome: 'Pera', codigo: 30, preco: 4.5, quantidade: 15 },
    { nome: 'Uva', codigo: 31, preco: 5.0, quantidade: 20 },
    { nome: 'Melancia', codigo: 32, preco: 10.0, quantidade: 5 },
    { nome: 'Abacaxi', codigo: 33, preco: 6.0, quantidade: 10 },
    { nome: 'Papel Higiênico', codigo: 34, preco: 15.0, quantidade: 12 },
    { nome: 'Sabonete', codigo: 35, preco: 2.5, quantidade: 50 },
    { nome: 'Detergente', codigo: 36, preco: 3.0, quantidade: 30 },
    { nome: 'Sabão em Pó', codigo: 37, preco: 12.0, quantidade: 20 },
    { nome: 'Amaciante', codigo: 38, preco: 8.0, quantidade: 18 },
    { nome: 'Desinfetante', codigo: 39, preco: 6.0, quantidade: 22 },
    { nome: 'Shampoo', codigo: 40, preco: 10.0, quantidade: 15 },
    { nome: 'Condicionador', codigo: 41, preco: 9.0, quantidade: 18 },
    { nome: 'Escova de Dente', codigo: 42, preco: 4.0, quantidade: 25 },
    { nome: 'Pasta de Dente', codigo: 43, preco: 3.5, quantidade: 30 },
    { nome: 'Água Mineral', codigo: 44, preco: 2.0, quantidade: 50 },
    { nome: 'Cerveja', codigo: 45, preco: 7.0, quantidade: 40 },
    { nome: 'Vinho', codigo: 46, preco: 30.0, quantidade: 12 },
    { nome: 'Whisky', codigo: 47, preco: 100.0, quantidade: 5 },
    { nome: 'Vodka', codigo: 48, preco: 25.0, quantidade: 20 },
    { nome: 'Tequila', codigo: 49, preco: 60.0, quantidade: 8 },
    { nome: 'Cachaça', codigo: 50, preco: 15.0, quantidade: 30 },
    { nome: 'Chocolate', codigo: 51, preco: 8.0, quantidade: 50 },
    { nome: 'Sorvete', codigo: 52, preco: 20.0, quantidade: 15 },
    { nome: 'Bolo', codigo: 53, preco: 25.0, quantidade: 10 },
    { nome: 'Pipoca', codigo: 54, preco: 3.5, quantidade: 35 },
    { nome: 'Batata Frita', codigo: 55, preco: 10.0, quantidade: 25 },
    { nome: 'Pizza', codigo: 56, preco: 30.0, quantidade: 20 },
    { nome: 'Hambúrguer', codigo: 57, preco: 12.0, quantidade: 30 },
    { nome: 'Salgadinho', codigo: 58, preco: 5.0, quantidade: 40 },
    { nome: 'Iogurte', codigo: 59, preco: 6.0, quantidade: 20 },
    { nome: 'Requeijão', codigo: 60, preco: 8.5, quantidade: 18 },
    { nome: 'Geléia', codigo: 61, preco: 7.0, quantidade: 22 },
    { nome: 'Granola', codigo: 62, preco: 10.0, quantidade: 25 },
    { nome: 'Aveia', codigo: 63, preco: 4.0, quantidade: 30 },
    { nome: 'Sucrilhos', codigo: 64, preco: 12.0, quantidade: 12 },
    { nome: 'Cereal', codigo: 65, preco: 10.0, quantidade: 15 },
    { nome: 'Leite Condensado', codigo: 66, preco: 6.5, quantidade: 28 },
    { nome: 'Creme de Leite', codigo: 67, preco: 4.5, quantidade: 30 },
    { nome: 'Margarina', codigo: 68, preco: 3.5, quantidade: 35 },
    { nome: 'Ketchup', codigo: 69, preco: 7.0, quantidade: 25 },
    { nome: 'Mostarda', codigo: 70, preco: 6.0, quantidade: 25 },
    { nome: 'Maionese', codigo: 71, preco: 8.0, quantidade: 15 },
    { nome: 'Barra de Cereal', codigo: 72, preco: 2.5, quantidade: 40 },
    { nome: 'Bebida Energética', codigo: 73, preco: 10.0, quantidade: 20 },
    { nome: 'Água de Coco', codigo: 74, preco: 4.0, quantidade: 30 },
    { nome: 'Guaraná Natural', codigo: 75, preco: 6.0, quantidade: 20 },
    { nome: 'Chá Gelado', codigo: 76, preco: 5.0, quantidade: 25 },
    { nome: 'Chá Verde', codigo: 77, preco: 6.5, quantidade: 18 },
    { nome: 'Azeite', codigo: 78, preco: 12.0, quantidade: 12 },
    { nome: 'Vinagre', codigo: 79, preco: 3.5, quantidade: 35 },
    { nome: 'Tempero', codigo: 80, preco: 2.0, quantidade: 50 },
    { nome: 'Canela', codigo: 81, preco: 1.5, quantidade: 50 },
    { nome: 'Cravo', codigo: 82, preco: 1.8, quantidade: 45 },
    { nome: 'Fermento', codigo: 83, preco: 2.5, quantidade: 40 },
    { nome: 'Coco Ralado', codigo: 84, preco: 3.0, quantidade: 35 },
    { nome: 'Gelatina', codigo: 85, preco: 1.2, quantidade: 60 },
    { nome: 'Pudim', codigo: 86, preco: 5.0, quantidade: 20 },
    { nome: 'Leite em Pó', codigo: 87, preco: 10.5, quantidade: 25 },
    { nome: 'Achocolatado', codigo: 88, preco: 8.0, quantidade: 30 },
    { nome: 'Sucrilhos de Chocolate', codigo: 89, preco: 12.0, quantidade: 12 },
    { nome: 'Doce de Leite', codigo: 90, preco: 7.5, quantidade: 25 },
    { nome: 'Chantilly', codigo: 91, preco: 15.0, quantidade: 10 },
    { nome: 'Frutas Secas', codigo: 92, preco: 20.0, quantidade: 15 },
    { nome: 'Castanhas', codigo: 93, preco: 25.0, quantidade: 12 },
    { nome: 'Nozes', codigo: 94, preco: 30.0, quantidade: 10 },
    { nome: 'Amendoim', codigo: 95, preco: 5.0, quantidade: 50 },
    { nome: 'Mel', codigo: 96, preco: 18.0, quantidade: 8 },
    { nome: 'Geleia de Morango', codigo: 97, preco: 7.0, quantidade: 30 },
    { nome: 'Ração para Cães', codigo: 98, preco: 80.0, quantidade: 12 },
    { nome: 'Ração para Gatos', codigo: 99, preco: 90.0, quantidade: 10 },
    { nome: 'Areia Higiênica', codigo: 100, preco: 15.0, quantidade: 20 },
];
